### ISSUE TITLE
ModuleNotFoundError    : from reTools import evaluation, mAPNo module named 'gnn_reranking'

### ISSUE THREAD

**Issue by newbie521** [Shuyu-XJTU/APTM#6]
(APTM) rwp@boot-desktop:~/Projects/APTM/APTM-main$ python3 run.py --task "itr_cuhk" --dist "f4" --output_dir "output/ft_cuhk" --checkpoint "output/pretrained/checkpoint_31.pth"
NNODES,  1
NPROC_PER_NODE,  4
MASTER_ADDR,  127.0.0.1
MASTER_PORT,  3000
NODE_RANK,  0
/home/rwp/anaconda3/envs/APTM/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "Retrieval.py", line 30, in <module>
    from reTools import evaluation, mAP
  File "/home/rwp/Projects/APTM/APTM-main/reTools.py", line 19, in <module>
    from gnn_reranking import gnn_reranking
ModuleNotFoundError: No module named 'gnn_reranking'
Traceback (most recent call last):
  File "Retrieval.py", line 30, in <module>
    from reTools import evaluation, mAP
  File "/home/rwp/Projects/APTM/APTM-main/reTools.py", line 19, in <module>
    from gnn_reranking import gnn_reranking
ModuleNotFoundError: No module named 'gnn_reranking'
Traceback (most recent call last):
  File "Retrieval.py", line 30, in <module>
Traceback (most recent call last):
  File "Retrieval.py", line 30, in <module>
    from reTools import evaluation, mAP
  File "/home/rwp/Projects/APTM/APTM-main/reTools.py", line 19, in <module>
    from gnn_reranking import gnn_reranking
ModuleNotFoundError    : from reTools import evaluation, mAPNo module named 'gnn_reranking'

  File "/home/rwp/Projects/APTM/APTM-main/reTools.py", line 19, in <module>
    from gnn_reranking import gnn_reranking
ModuleNotFoundError: No module named 'gnn_reranking'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1095169) of binary: /home/rwp/anaconda3/envs/APTM/bin/python3
Traceback (most recent call last):
  File "/home/rwp/anaconda3/envs/APTM/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rwp/anaconda3/envs/APTM/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rwp/anaconda3/envs/APTM/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/rwp/anaconda3/envs/APTM/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/rwp/anaconda3/envs/APTM/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/rwp/anaconda3/envs/APTM/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/rwp/anaconda3/envs/APTM/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/rwp/anaconda3/envs/APTM/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
          Retrieval.py FAILED          
=======================================
Root Cause:
[0]:
  time: 2023-09-07_20:03:40
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 1095169)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2023-09-07_20:03:40
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 1095170)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[2]:
  time: 2023-09-07_20:03:40
  rank: 2 (local_rank: 2)
  exitcode: 1 (pid: 1095171)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[3]:
  time: 2023-09-07_20:03:40
  rank: 3 (local_rank: 3)
  exitcode: 1 (pid: 1095172)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************

**Comment by newbie521** [comment]
有人知道为什么吗
